const PDFDocument = require("pdfkit");
const path = require("path");
const QRCode = require("qrcode");

const generateStudentSlip = async (student, res) => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${student.studentId}-registration-slip.pdf`
  );

  doc.pipe(res);

  // ==========================
  // Helper function
  // ==========================

  const formatDate = (date) =>
    new Date(date).toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    });

  const addRow = (label, value) => {
    doc
      .font("Helvetica-Bold")
      .fontSize(12)
      .text(label, {
        continued: true,
      });

    doc
      .font("Helvetica")
      .text(value || "N/A");

    doc.moveDown(0.5);
  };

  // ==========================
  // School Logo
  // ==========================

  const logoPath = path.join(__dirname, "../assets/logo.jpeg");

  doc.image(logoPath, 245, 30, {
    width: 100,
  });

  doc.moveDown(7);

  // ==========================
  // Header
  // ==========================

  doc
    .font("Helvetica-Bold")
    .fontSize(22)
    .text("TENNESON COMPREHENSIVE COLLEGE", {
      align: "center",
    });

  doc
    .fontSize(16)
    .text("STUDENT REGISTRATION SLIP", {
      align: "center",
    });

  doc.moveDown();

  // ==========================
  // Divider
  // ==========================

  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();

  doc.moveDown();

  // ==========================
  // Student Details
  // ==========================

  addRow("Student ID: ", student.studentId);

  addRow(
    "Name: ",
    `${student.firstName} ${student.otherName || ""} ${student.lastName}`
  );

  addRow("Gender: ", student.gender);

  addRow(
    "Date of Birth: ",
    formatDate(student.dateOfBirth)
  );

  addRow(
    "Admission Date: ",
    formatDate(student.admissionDate)
  );

  addRow("Class: ", student.currentClass);

  addRow("Session: ", student.session);

  addRow("Parent Name: ", student.parentName);

  addRow("Parent Phone: ", student.parentPhone);

  // ==========================
  // Divider
  // ==========================

  doc.moveDown();

  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .stroke();

  doc.moveDown();

  // ==========================
  // Important Notice
  // ==========================

  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .text(
      "Use this Student ID when creating your account on the main school portal.",
      {
        align: "center",
      }
    );

  doc.moveDown();

  doc
    .font("Helvetica")
    .fontSize(11)
    .text(
      "This document confirms that the student ID belongs to a registered student of Tenneson College.",
      {
        align: "center",
      }
    );

  doc.moveDown(3);

  // ==========================
  // Signature Section
  // ==========================

  const signatureY = doc.y;

  doc.text("________________________", 60, signatureY);
  doc.text("Principal's Signature", 75);

  doc.text("________________________", 330, signatureY);
  doc.text("School Stamp", 380);

  doc.moveDown(4);

  // ==========================
  // Footer
  // ==========================

  doc
    .fontSize(10)
    .fillColor("gray")
    .text("Generated by Tenneson School Portal", {
      align: "center",
    });


    const verifyUrl = `${process.env.FRONTEND_URL}/verify/${student.studentId}`;

const qrCode = await QRCode.toDataURL(verifyUrl);

doc.moveDown(2);

doc
  .fontSize(12)
  .text("Scan to verify student", {
    align: "center",
  });

doc.image(qrCode, {
  fit: [120, 120],
  align: "center",
});

  doc.end();
};

module.exports = generateStudentSlip;